name: Run Weekly Database Update Automation

on:
  #schedule:
  #  cron: '0 9 * * 6'  # 9am every Saturday
  push:
    branches:
      - oakley/weekly-automation 

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setup minimum python version compatible with project
        uses: actions/setup-python@v2
        with:  # 3.6.15 is available on ubuntu-latest by default, cuts down on run time
          python-version: 3.6.15  
      - name: Load cached pypoetry installation and virtualenvs
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: local-pypoetry
      - name: Install pypoetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.1.13
          virtualenvs-path: ~/.local/opt/virtualenvs
      - name: Install/update project dependencies
        run: poetry install --no-interaction
      - name: Attempt database update
        # run: poetry run python pdh_json_updater/update_json.py
        run: |
          echo "test" >> pauper_commander.json
          echo "test" >> last_update_metadata.json
      - name: Check if database update occurred
        id: check-update
        run: echo "::set-output name=was-updated::$(git diff --quiet pauper_commander.json; echo $?)"
      - name: Get current date
        id: get-date
        if: steps.check-update.was-updated == '1'
        run: echo "::set-output name=current-date::$(date +%Y-%m-%d)"
      - name: Submit pull request for database updates
        if: steps.check-update.was-updated == '1'
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: pauper_commander.json, last_update_metadata.json
          branch: database-update/${{ steps.get-date.current-date }}
          commit-message: Database update ${{ steps.get-date.current-date }}
          title: Database update ${{ steps.get-date.current-date }}
          reviewers: oakreid, chevEldrid

